[package]
name = "file_randomizer"
version = "0.1.0"
edition = "2021"

[dependencies]
confy = "1.0.0"
dirs = "6.0.0"
eframe = "0.31.1"
env_logger = "0.11.8"
flexbuffers = "25.2.10"
open = "5.3.2"
rand = "0.9.1"
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"] }
