name: Build with Nuitka
on: [push]

jobs:
  pyinstaller-build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:

jobs:
  build:

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.3"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build a requirements.txt for pyinstaller
        run: uv pip compile pyproject.toml -o requirements.txt

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'FileRandomizer'
          options: --onefile, --name "FileRandomizer", --windowed, 
