name: Build
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install tkinter
        run: sudo apt-get install --yes python3-tk

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build a requirements.txt for pyinstaller
        run: uv pip compile pyproject.toml -o requirements.txt

      - name: Install build requirements
        run: uv sync --group build

      - name: Run pyinstaller
        run: uv run pyinstaller --onedir --windowed --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.filedialog file_randomizer/file_randomizer.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: dist/*
          include-hidden-files: true          
