name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        build: [linux-x86_64, linux-aarch64, macos-x86_64, macos-aarch64, win]
        include:
        - build: linux-x86_64
          os: ubuntu-24.04
        - build: linux-aarch64
          os: ubuntu-24.04-arm
        - build: macos-x86_64
          os: macos-13
        - build: macos-aarch64
          os: macos-14
        - build: win
          os: windows-2022
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: file_randomizer.${{ matrix.build }}
        path: |
          target/release/file_randomizer
          target/release/file_randomizer.exe
  
